#!/bin/bash

# read words from standard input into an array
readarray -t words

# count the number of occurrences of each word
declare -A word_counts
for word in "${words[@]}"; do
    ((word_counts[$word]++))
done

# print words that appear exactly once
for word in "${!word_counts[@]}"; do
    if ((word_counts[$word] == 1)); then
        echo "$word"
    fi
done | sort  # sort the output

